// AUTOGENERATED FILE
// This file was generated from bracket.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface FinkelBracketActionDict<T> extends BaseActionDict<T> {
  Content?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WS?: (this: NonterminalNode, arg0: IterationNode) => T;
  Article?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Adjective?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Adverb?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Conjunction?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Interjection?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Numeral?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Participle?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Preposition?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Pronoun?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Verb?: (this: NonterminalNode, arg0: TerminalNode) => T;
  GenderMarker?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  GenderHead?: (this: NonterminalNode, arg0: TerminalNode) => T;
  GenderTail?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Prefix?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Pronunciation?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  Definition?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  Clause?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Connotations?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  GrammarNote?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  Idiom?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  Origin?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  UsageNote?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: NonterminalNode) => T;
  BracketText?: (this: NonterminalNode, arg0: IterationNode) => T;
  BracketRest?: (this: NonterminalNode, arg0: NonterminalNode) => T;
}

export interface FinkelBracketSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: FinkelBracketActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: FinkelBracketActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: FinkelBracketActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: FinkelBracketActionDict<T>): this;
}

export interface FinkelBracketGrammar extends Grammar {
  createSemantics(): FinkelBracketSemantics;
  extendSemantics(superSemantics: FinkelBracketSemantics): FinkelBracketSemantics;
}

declare const grammar: FinkelBracketGrammar;
export default grammar;

