// AUTOGENERATED FILE
// This file was generated from entry.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface FinkelEntryActionDict<T> extends BaseActionDict<T> {
  entryLine?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  sequence?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  component?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  componentJoin?: (this: NonterminalNode, arg0: IterationNode | NonterminalNode) => T;
  selfDelimiting?: (this: NonterminalNode, arg0: TerminalNode) => T;
  delim?: (this: NonterminalNode, arg0: IterationNode) => T;
  ws?: (this: NonterminalNode, arg0: IterationNode) => T;
  form?: (this: NonterminalNode, arg0: IterationNode) => T;
  formChunk?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  formSpelling?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: NonterminalNode, arg3: TerminalNode) => T;
  spellingBase?: (this: NonterminalNode, arg0: IterationNode) => T;
  spellingChar?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  formBase?: (this: NonterminalNode, arg0: IterationNode) => T;
  formChar?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  macro?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  macroArgument?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode) => T;
  macroSymbolChars?: (this: NonterminalNode, arg0: IterationNode) => T;
  macroSymbolChar?: (this: NonterminalNode, arg0: TerminalNode) => T;
  bracketedData?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  bracketInner?: (this: NonterminalNode, arg0: IterationNode) => T;
  trailingComment?: (this: NonterminalNode, arg0: IterationNode, arg1: TerminalNode, arg2: IterationNode) => T;
}

export interface FinkelEntrySemantics extends Semantics {
  addOperation<T>(name: string, actionDict: FinkelEntryActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: FinkelEntryActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: FinkelEntryActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: FinkelEntryActionDict<T>): this;
}

export interface FinkelEntryGrammar extends Grammar {
  createSemantics(): FinkelEntrySemantics;
  extendSemantics(superSemantics: FinkelEntrySemantics): FinkelEntrySemantics;
}

declare const grammar: FinkelEntryGrammar;
export default grammar;

